# WebAssembly XCircuit build (second real showcase app).
#
# XCircuit has two build modes. The native fragment (mk/xcircuit.mk) builds the
# Tcl/Tk variant, which loads xcircuit as a shared Tcl extension -- a model with
# no wasm equivalent. This fragment builds the OTHER mode: the standalone Xt
# application driven by XCircuit's own bundled Xw widget set (Xw/libxcXw.a), no
# Tcl. configure selects it whenever neither --with-tcl nor python is present.
#
# Unlike xnedit (a hand-written Makefile), XCircuit cross-configures through
# autotools, so the wall is AC_PATH_XTRA and the AC_CHECK_LIB probes: each does a
# real link test, and under emcc -lX11 does not link on its own because the core
# archive references SDL and pixman symbols that only -sUSE_SDL=2 / -lpixman-1
# provide. The fix is to feed that backing into the configure environment (CFLAGS
# carries -sUSE_SDL=2, LIBS carries pixman + -lm), so every conftest links, plus
# --host=wasm32-unknown-emscripten so autoconf skips the run-only tests.
#
# Wasm-specific arrangements, mirroring mk/wasm-xnedit.mk:
#  - Lib aliases: emcc resolves -l<name> to lib<name>.a. libX11/Xt/Xpm alias the
#    real wasm archives; libICE/libSM alias tiny archives built here from
#    compat/ice-compat.c and compat/sm-compat.c (the same stubs the native
#    libICE-compat / libSM-compat wrap).
#  - The core is added to the link as a POSITIONAL archive, not through -lX11:
#    emcc treats X11 as a host system library it does not provide and silently
#    drops -lX11, which would leave every core symbol undefined.
#  - menudep is a build-time codegen tool that emits menudep.h (menu wiring) for
#    eight sources. Under emmake CC=emcc it would compile to a wasm binary that
#    cannot run natively to write the header, so it is built and run with HOST_CC
#    first (the makestrs pattern from mk/wasm-motif.mk); its output depends only on
#    the menu definitions, so the host SIZEOF_* values are immaterial, but the
#    menu-gating feature defines (HAVE_XPM, ASG, LGF, INPUT_FOCUS) must match the
#    wasm compile or the header omits entries the sources reference.
#  - AR=emar overrides the ar the configure probe baked into the subdir Makefiles:
#    the host ar/ranlib cannot archive wasm bitcode objects and silently emits an
#    empty Xw/libxcXw.a, so its widget classes go undefined at link.
#  - The staged git checkout gives every file one mtime, so a Makefile.am can read
#    as no older than its Makefile.in and fire the always-on automake regeneration
#    rule (XCircuit has no AM_MAINTAINER_MODE), which is not installed here. The
#    generated byproducts are touched newer than their sources after patching so no
#    regen runs, unless a patch edits an autotools source (then let it rebuild).
#  - Output: configure links -o xcircuit (a plain name), so emcc emits the JS
#    loader there plus xcircuit.wasm and, from --preload-file, xcircuit.data. A
#    post step copies the JS to xcircuit.js and wraps it in the themed launcher.

ifeq ($(WASM),1)

XCIRCUIT_WASM_DIR := $(OUT)/wasm-xcircuit
XCIRCUIT_WASM_WORK := $(XCIRCUIT_WASM_DIR)/source
XCIRCUIT_WASM_SYSROOT := $(XCIRCUIT_WASM_DIR)/sysroot
XCIRCUIT_WASM_LIBDIR := $(XCIRCUIT_WASM_DIR)/lib-aliases
XCIRCUIT_WASM_PCDIR := $(XCIRCUIT_WASM_DIR)/pkgconfig
XCIRCUIT_WASM_STAMP := $(XCIRCUIT_WASM_DIR)/.build-stamp
XCIRCUIT_WASM_HTML := $(OUT)/xcircuit.html
XCIRCUIT_WASM_LOG := $(abspath $(XCIRCUIT_WASM_DIR))/build.log

# Tiny session-management archives: the standalone link names -lSM -lICE, and
# those symbols are absent from the wasm core. Built from the same compat stubs
# the native libICE-compat / libSM-compat objects use.
XCIRCUIT_WASM_ICE := $(XCIRCUIT_WASM_LIBDIR)/libICE.a
XCIRCUIT_WASM_SM := $(XCIRCUIT_WASM_LIBDIR)/libSM.a

# Real archives the aliases point at. Absolute so the symlink target stays valid
# regardless of whether OUT is a relative or absolute path.
XCIRCUIT_WASM_REAL := libX11.a:$(abspath $(TARGET)) \
    libXt.a:$(abspath $(LIBXT_TARGET)) libXpm.a:$(abspath $(LIBXPM_TARGET))

# Absolute include set: configure and the recursive Xw build cd into subdirs, so
# every -I must be absolute. Deliberately not WASM_LIBXT_TEST_CPPFLAGS (its
# -DHAVE_CONFIG_H is libXt-internal and would misdirect XCircuit's includes).
XCIRCUIT_WASM_INC := -I$(abspath $(XCIRCUIT_WASM_SYSROOT)) \
    -I$(abspath $(OUT)/upstream/include) -I$(abspath include) \
    -I$(abspath include/libxt-build) -DNARROWPROTO \
    $(SDL_CPPFLAGS) $(PIXMAN_CFLAGS)

# XCircuit predates C99 and trips emcc's clang on implicit ints, missing
# prototypes, and the Xw widget set's concrete-widget-pointer casts. Drop those
# to warnings, matching the native fragment's gcc/clang gate but with only the
# clang spellings (emcc is always clang).
XCIRCUIT_WASM_CFLAGS = $(OPTFLAGS) $(SDL_PORT_FLAGS) -D_DEFAULT_SOURCE \
    -D_GNU_SOURCE -Wno-error=implicit-int \
    -Wno-error=implicit-function-declaration \
    -Wno-error=incompatible-pointer-types \
    -Wno-error=incompatible-function-pointer-types \
    -Wno-deprecated-non-prototype -Wno-error=int-conversion \
    $(XCIRCUIT_WASM_INC) $(CFLAGS_EXTRA)

# Backing that makes configure's link tests resolve: pixman plus -lm (SDL rides
# in through CFLAGS). The alias dir is on the search path so -lXt/-lXpm/-lSM/-lICE
# resolve too.
XCIRCUIT_WASM_CONF_LIBS := $(PIXMAN_LIBS) -lm
XCIRCUIT_WASM_CONF_LDFLAGS := -L$(abspath $(XCIRCUIT_WASM_LIBDIR))

# Link flags fed through LDFLAGS to the final xcircuit link: the browser yield
# objects and poll/select wrap under ASYNCIFY, the font preload, memory growth,
# and the Xt and core archives positionally. emcc silently drops -lX11 (a host
# library it does not provide), and the standalone configure never emits -lXt at
# all, so both are supplied as positional archives rather than through -l; Xpm,
# SM, and ICE survive as -l and resolve from the alias dir. Xt precedes the core
# so a dependant-before-dependency order holds even though wasm-ld is lenient.
# EMULATE_FUNCTION_POINTER_CASTS wraps the Xt/Xw callback casts (XtEventHandler,
# XtCallbackProc registered from prototypeless helpers): native calling
# conventions tolerate the mismatch, but wasm's typed call_indirect traps on it,
# which otherwise aborts init before the first window and leaves a blank canvas.
# XCircuit renders text from its OWN vector fonts (fonts/*.xfe) and encoding files,
# not the DejaVu TTF; preload its lib tree at the baked BUILTINS_DIR so the font
# loader finds them (without it the window paints but every label errors out).
# tcl/ and python/ are excluded: the wasm build is --without-tcl --without-python,
# so those interpreter trees are dead weight in the .data payload.
XCIRCUIT_WASM_LIB_PRELOAD := --preload-file \
    $(abspath $(XCIRCUIT_SRC_DIR))/lib@/usr/local/lib/xcircuit-3.10 \
    --exclude-file $(abspath $(XCIRCUIT_SRC_DIR))/lib/tcl \
    --exclude-file $(abspath $(XCIRCUIT_SRC_DIR))/lib/python
XCIRCUIT_WASM_LDFLAGS = -L$(abspath $(XCIRCUIT_WASM_LIBDIR)) \
    $(abspath $(WASM_APP_YIELD_OBJS)) -sASYNCIFY \
    -Wl,--wrap=poll -Wl,--wrap=select -sALLOW_MEMORY_GROWTH \
    -sEMULATE_FUNCTION_POINTER_CASTS=1 \
    $(WASM_FONT_PRELOAD) $(XCIRCUIT_WASM_LIB_PRELOAD) \
    $(abspath $(LIBXT_TARGET)) $(abspath $(TARGET)) \
    $(PIXMAN_LIBS)

# Emit one wasm .pc so PKG_CHECK_MODULES([fontconfig]) succeeds; the symbols live
# in the core, so Libs is empty. Description is mandatory or pkg-config ignores it
# and falls back to the host fontconfig.
define xcircuit_wasm_pc
	@{ echo "Name: $(1)"; echo "Description: libx11-compat wasm $(1)"; \
	   echo "Version: 1.0"; echo "Cflags: $(XCIRCUIT_WASM_INC)"; \
	   echo "Libs:"; } > $(XCIRCUIT_WASM_PCDIR)/$(1).pc
endef

$(XCIRCUIT_WASM_STAMP): $(XCIRCUIT_SOURCE_STAMP) $(XCIRCUIT_PATCHES) \
    compat/ice-compat.c compat/sm-compat.c $(TARGET) $(LIBXT_TARGET) \
    $(LIBXPM_TARGET) $(WASM_APP_YIELD_OBJS) $(WASM_FONT_STAMP) \
    $(WASM_SHELL) mk/wasm-xcircuit.mk
	@echo "  SYSROOT xcircuit (wasm)"
	$(Q)rm -rf $(XCIRCUIT_WASM_DIR)
	$(Q)mkdir -p $(XCIRCUIT_WASM_SYSROOT)/X11 $(XCIRCUIT_WASM_LIBDIR) \
	    $(XCIRCUIT_WASM_PCDIR)
	$(Q)for e in $(abspath $(OUT)/upstream/include)/X11/*; do \
	    ln -sf "$$e" "$(XCIRCUIT_WASM_SYSROOT)/X11/$$(basename "$$e")"; done
	$(Q)for e in $(abspath include)/X11/*; do \
	    b=$$(basename "$$e"); [ -e "$(XCIRCUIT_WASM_SYSROOT)/X11/$$b" ] || \
	        ln -sf "$$e" "$(XCIRCUIT_WASM_SYSROOT)/X11/$$b"; done
	@echo "  AR      xcircuit wasm libICE/libSM"
	$(Q)$(CC) $(XCIRCUIT_WASM_CFLAGS) -c compat/ice-compat.c \
	    -o $(XCIRCUIT_WASM_DIR)/ice.o
	$(Q)$(CC) $(XCIRCUIT_WASM_CFLAGS) -c compat/sm-compat.c \
	    -o $(XCIRCUIT_WASM_DIR)/sm.o
	$(Q)$(AR) rcs $(XCIRCUIT_WASM_ICE) $(XCIRCUIT_WASM_DIR)/ice.o
	$(Q)$(AR) rcs $(XCIRCUIT_WASM_SM) $(XCIRCUIT_WASM_DIR)/sm.o
	@echo "  ALIAS   xcircuit wasm libs"
	$(Q)for pair in $(XCIRCUIT_WASM_REAL); do \
	    a="$${pair%%:*}"; t="$${pair##*:}"; \
	    ln -sf "$$t" "$(XCIRCUIT_WASM_LIBDIR)/$$a"; done
	$(call xcircuit_wasm_pc,fontconfig)
	@echo "  STAGE   xcircuit source (wasm)"
	$(Q)rm -rf $(XCIRCUIT_WASM_WORK) && mkdir -p $(XCIRCUIT_WASM_WORK)
	$(Q)tar --exclude .git -cf $(XCIRCUIT_WASM_DIR)/.src.tar \
	    -C $(XCIRCUIT_SRC_DIR) .
	$(Q)tar -xf $(XCIRCUIT_WASM_DIR)/.src.tar -C $(XCIRCUIT_WASM_WORK)
	$(Q)rm -f $(XCIRCUIT_WASM_DIR)/.src.tar
	$(Q)set -e; for patch in $(XCIRCUIT_PATCHES); do \
	    patch -d $(XCIRCUIT_WASM_WORK) -p1 < "$$patch"; done
	$(Q)set -e; touch_ok=1; \
	for patch in $(XCIRCUIT_PATCHES); do \
	    if grep -Eq '^(\+\+\+|---) .*[/ ](Makefile\.am|configure\.(ac|in)|[^/ ]+\.m4)([[:space:]]|$$)' "$$patch"; then \
	        echo "  SKIP    autotools mtime touch ($$patch edits an autotools source)"; \
	        touch_ok=0; \
	    fi; \
	done; \
	if [ "$$touch_ok" = 1 ]; then \
	    find $(XCIRCUIT_WASM_WORK) \( -name aclocal.m4 -o -name configure \
	        -o -name config.h.in -o -name 'Makefile.in' \) -exec touch {} +; \
	fi
	@echo "  CONF    xcircuit (wasm)"
	$(Q)cd $(XCIRCUIT_WASM_WORK) && \
	    PKG_CONFIG_LIBDIR=$(abspath $(XCIRCUIT_WASM_PCDIR)) \
	    PKG_CONFIG_PATH=$(abspath $(XCIRCUIT_WASM_PCDIR)) \
	    env -u MAKEFLAGS -u MFLAGS \
	    emconfigure ./configure --host=wasm32-unknown-emscripten \
	        --without-tcl --without-cairo --without-python --without-gs \
	        --with-xpm=$(abspath $(dir $(TARGET))) \
	        --x-includes=$(abspath $(XCIRCUIT_WASM_SYSROOT)) \
	        --x-libraries=$(abspath $(XCIRCUIT_WASM_LIBDIR)) \
	        CC='$(CC)' AR='emar' \
	        CFLAGS='$(XCIRCUIT_WASM_CFLAGS)' \
	        CPPFLAGS='$(XCIRCUIT_WASM_INC)' \
	        LDFLAGS='$(XCIRCUIT_WASM_CONF_LDFLAGS)' \
	        LIBS='$(XCIRCUIT_WASM_CONF_LIBS)' \
	        >$(XCIRCUIT_WASM_LOG) 2>&1 || { \
	            echo "  FAIL    see $(XCIRCUIT_WASM_LOG)" >&2; \
	            tail -60 $(XCIRCUIT_WASM_LOG) >&2; exit 1; }
	$(Q)find $(XCIRCUIT_WASM_WORK) \( -name config.status -o -name Makefile \) \
	    -exec touch {} +
	@echo "  HOSTGEN xcircuit menudep.h (native)"
	$(Q)cd $(XCIRCUIT_WASM_WORK) && $(HOST_CC) -O2 -I. \
	    -I$(abspath include) -I$(abspath $(OUT)/upstream/include) \
	    -I$(abspath include/libxt-build) -D_DEFAULT_SOURCE \
	    -DHAVE_XPM=1 -DASG -DLGF=1 -DINPUT_FOCUS=1 \
	    -DSIZEOF_VOID_P=8 -DSIZEOF_UNSIGNED_INT=4 -DSIZEOF_UNSIGNED_LONG=8 \
	    -DSIZEOF_UNSIGNED_LONG_LONG=8 -Wno-implicit-int \
	    -Wno-implicit-function-declaration -Wno-incompatible-pointer-types \
	    -c menudep.c -o menudep.o
	$(Q)cd $(XCIRCUIT_WASM_WORK) && $(HOST_CC) -o menudep menudep.o && ./menudep
	$(Q)touch $(XCIRCUIT_WASM_WORK)/menudep.o $(XCIRCUIT_WASM_WORK)/menudep \
	    $(XCIRCUIT_WASM_WORK)/menudep.h
	@echo "  MAKE    xcircuit (wasm)"
	$(Q)env -u MAKEFLAGS -u MFLAGS \
	    emmake $(MAKE) -C $(XCIRCUIT_WASM_WORK) AR='emar' RANLIB='emranlib' \
	    LDFLAGS='$(XCIRCUIT_WASM_LDFLAGS)' \
	    >>$(XCIRCUIT_WASM_LOG) 2>&1 || { \
	        echo "  FAIL    see $(XCIRCUIT_WASM_LOG)" >&2; \
	        tail -60 $(XCIRCUIT_WASM_LOG) >&2; exit 1; }
	$(Q)if [ ! -s $(XCIRCUIT_WASM_WORK)/xcircuit.wasm ]; then \
	        echo "  FAIL    xcircuit.wasm not produced; see $(XCIRCUIT_WASM_LOG)" >&2; \
	        tail -60 $(XCIRCUIT_WASM_LOG) >&2; exit 1; fi
	$(Q)touch $@

$(XCIRCUIT_WASM_HTML): $(XCIRCUIT_WASM_STAMP) $(WASM_SHELL) mk/wasm-xcircuit.mk
	@echo "  HTML    $@"
	$(Q)cp $(XCIRCUIT_WASM_WORK)/xcircuit $(OUT)/xcircuit.js
	$(Q)cp $(XCIRCUIT_WASM_WORK)/xcircuit.wasm $(OUT)/xcircuit.wasm
	$(Q)test ! -e $(XCIRCUIT_WASM_WORK)/xcircuit.data || \
	    cp $(XCIRCUIT_WASM_WORK)/xcircuit.data $(OUT)/xcircuit.data
	$(Q)sed 's#{{{ SCRIPT }}}#<script src="xcircuit.js"></script>#' \
	    $(WASM_SHELL) > $@

.PHONY: xcircuit-wasm
xcircuit-wasm: $(XCIRCUIT_WASM_HTML)

endif

.PHONY: check-wasm-xcircuit
## Build the wasm XCircuit browser artifact (skips when emcc is unavailable)
check-wasm-xcircuit:
	$(Q)if ! command -v emcc >/dev/null 2>&1; then \
	    echo "  SKIP    check-wasm-xcircuit (emcc not found)"; \
	    exit 0; \
	fi; \
	$(MAKE) WASM=1 xcircuit-wasm || exit 1; \
	for f in $(OUT)/xcircuit.html $(OUT)/xcircuit.js $(OUT)/xcircuit.wasm \
	         $(OUT)/xcircuit.data; do \
	    if [ ! -s "$$f" ]; then echo "check-wasm-xcircuit: missing $$f" >&2; exit 1; fi; \
	done; \
	case `file -b $(OUT)/xcircuit.wasm` in \
	    *WebAssembly*) ;; \
	    *) echo "check-wasm-xcircuit: not a wasm module" >&2; exit 1;; \
	esac; \
	if command -v node >/dev/null 2>&1; then \
	    node scripts/wasm-node-smoke.mjs $(OUT)/xcircuit.wasm || exit 1; \
	    node scripts/wasm-paint-check.mjs $(OUT) xcircuit || exit 1; \
	else \
	    if [ "$${WASM_PAINT_REQUIRED:-0}" = 1 ]; then \
	        echo "check-wasm-xcircuit: node missing for required paint check" >&2; exit 1; \
	    fi; \
	    echo "  WARN    check-wasm-xcircuit: node missing, skipped module smoke" >&2; \
	fi; \
	echo "  OK      check-wasm-xcircuit (xcircuit cross-compiled to a wasm module)"
