#!/usr/bin/env python3
"""Generate a C source array from a 6x13 / 7x14 / similar 1-byte-per-row BDF.

Output is a static const unsigned char [CHAR_COUNT][HEIGHT] array suitable
for #include into src/font.c so the fixed-bitmap renderer does not need
the BDF file at runtime. Only the first CHAR_COUNT encodings (default 128)
are decoded. Rows that do not appear in the source remain 0.
"""

import argparse
import sys
from pathlib import Path


def decode_bdf(text: str, char_count: int, height: int):
    rows = [[0] * height for _ in range(char_count)]
    encoding = None
    bitmap_row = -1
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("STARTCHAR"):
            encoding = None
            bitmap_row = -1
            continue
        if stripped.startswith("ENCODING "):
            try:
                encoding = int(stripped.split()[1])
            except (IndexError, ValueError):
                encoding = None
            continue
        if stripped == "BITMAP" or stripped.startswith("BITMAP"):
            if encoding is not None and 0 <= encoding < char_count:
                bitmap_row = 0
            else:
                bitmap_row = -1
            continue
        if stripped.startswith("ENDCHAR"):
            bitmap_row = -1
            continue
        if bitmap_row >= 0 and bitmap_row < height:
            token = stripped.split()[0] if stripped else ""
            if len(token) in (1, 2) and all(
                c in "0123456789abcdefABCDEF" for c in token
            ):
                rows[encoding][bitmap_row] = int(token, 16)
                bitmap_row += 1
    return rows


def emit(rows, char_count: int, height: int, name: str):
    out = []
    out.append("/* Generated by scripts/embed-bdf-font.py. Do not edit. */")
    out.append(
        "/* Source: X.Org font-misc-misc 6x13.bdf, the classic -misc-fixed " "font. */"
    )
    out.append(
        "/* Fetched and regenerated on demand by mk/font-data.mk; the URL and "
        "digest live there. */"
    )
    out.append(f"static const unsigned char {name}[{char_count}][{height}] = {{")
    for ch, row_bytes in enumerate(rows):
        joined = ", ".join(f"0x{b:02x}" for b in row_bytes)
        comma = "," if ch + 1 < char_count else ""
        out.append(f"    {{ {joined} }}{comma}")
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("bdf", type=Path)
    parser.add_argument("--char-count", type=int, default=128)
    parser.add_argument("--height", type=int, default=13)
    parser.add_argument("--name", default="EMBEDDED_FIXED_BITMAP_ROWS")
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    rows = decode_bdf(args.bdf.read_text(), args.char_count, args.height)
    args.out.write_text(emit(rows, args.char_count, args.height, args.name))


if __name__ == "__main__":
    sys.exit(main())
