#!/bin/sh
# Fetch a pinned ANGLE source tree with plain git (no gn/gclient/depot_tools).
# The commit is pinned so the awk .gni source extraction in mk/angle.mk stays
# stable. A shallow single-commit fetch keeps the download small.
#
# The pin lives in scripts/angle-pin.txt as the single source of truth; this
# script regenerates the pin-derived gn shim (tools/angle-compat/angle_commit.h)
# from it after fetching, so the two cannot drift.
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
DEST="$ROOT/third_party/angle"
URL="https://chromium.googlesource.com/angle/angle"
PIN="$(cat "$ROOT/scripts/angle-pin.txt")"
COMMIT_H="$ROOT/tools/angle-compat/angle_commit.h"

write_commit_header() {
    cat >"$COMMIT_H" <<EOF
#ifndef LIBX11_COMPAT_ANGLE_COMMIT_H_
#define LIBX11_COMPAT_ANGLE_COMMIT_H_

/* Generated by scripts/fetch-angle.sh from scripts/angle-pin.txt. Do not edit;
 * bump the pin file and re-run make fetch-angle.
 */
#define ANGLE_COMMIT_HASH "$PIN"
#define ANGLE_COMMIT_HASH_SIZE 40
#define ANGLE_COMMIT_POSITION 0

#endif
EOF
}

if [ -d "$DEST/.git" ]; then
    current="$(git -C "$DEST" rev-parse HEAD 2>/dev/null || echo none)"
    if [ "$current" = "$PIN" ]; then
        write_commit_header
        echo "angle already fetched at $PIN"
        exit 0
    fi
    echo "angle at $current, expected $PIN; re-fetching" >&2
fi

mkdir -p "$DEST"
git -C "$DEST" init -q
git -C "$DEST" remote add origin "$URL" 2>/dev/null \
    || git -C "$DEST" remote set-url origin "$URL"
git -C "$DEST" fetch --depth=1 origin "$PIN"
git -C "$DEST" checkout -q --detach FETCH_HEAD

current="$(git -C "$DEST" rev-parse HEAD)"
if [ "$current" != "$PIN" ]; then
    echo "angle fetched $current, expected $PIN" >&2
    exit 1
fi
write_commit_header
echo "angle fetched at $PIN"
